# Generated by Django 2.2.1 on 2019-05-09 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lhs', models.CharField(db_column='lhs', max_length=50)),
                ('rhs', models.CharField(db_column='rhs', max_length=10)),
                ('min_age', models.IntegerField(db_column='min_age')),
                ('max_age', models.IntegerField(db_column='max_age')),
                ('support', models.FloatField(db_column='support')),
                ('confidence', models.FloatField(db_column='confidence')),
                ('num_accepted', models.IntegerField(db_column='num_accepted')),
                ('num_rejected', models.IntegerField(db_column='num_rejected')),
            ],
            options={
                'db_table': 'rules',
                'unique_together': {('rhs', 'lhs', 'min_age', 'max_age')},
            },
        ),
    ]
