# Generated by Django 2.2.1 on 2019-10-02 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='selectable',
            field=models.BooleanField(db_column='selectable', default=True),
        ),
    ]
